backend:
  name: github
  repo: patrickgrey/carolinehunterart
  branch: main # The branch to update (optional; defaults to master)
media_folder: "website-source/images" # Media files will be stored in the repo under images/uploads
collections:
  - name: "pictures" # Used in routes, e.g., /admin/collections/blog
    label: "Pictures" # Used in the UI
    folder: "admin/pictures" # The path to the folder where the documents are stored
    create: true
    extension : "json"
    fields: # The fields for each document, usually in front matter
      - { label: "Painting", name: "image", widget: "image" }
      - { label: "Alternative text", name: "altText", widget: "string" }
      - { label: "Caption", name: "caption", widget: "string" }